### ISSUE TITLE
Cookbook failing under chef-client 12.1

### ISSUE THREAD

**Issue by agperson** [opscode-cookbooks/chef-client#285]
With the latest chef-client release this cookbook is failing on CentOS and Amazon Linux (and possibly elsewhere?) due to an issue in the IIS cookbook.  Easily replicated with a `kitchen converge service-systemd-centos-70`  Captured in opscode-cookbooks/iis#149

**Comment by btm** [comment]
This didn't replicate for me, but the iis cookbook isn't in this run list either?

```
       Transferring files to <service-systemd-centos-70>
       Starting Chef Client, version 12.1.1
       [2015-03-10T17:01:21+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["chef-client::systemd_service"]
       Synchronizing Cookbooks:
         - chef-client
         - cron
         - windows
         - chef_handler
         - logrotate
       Compiling Cookbooks...
       Converging 8 resources
       Recipe: chef-client::systemd_service
        (up to date)
         * directory[/var/cache/chef] action create (up to date)
         * directory[/var/lib/chef] action create (up to date)
         * directory[/var/log/chef] action create (up to date)
         * directory[/etc/chef] action create (up to date)
        (up to date)
         * template[/etc/sysconfig/chef-client] action create (up to date)
        (up to date)
        (up to date)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/9 resources updated in 7.456092205 seconds
       Finished converging <service-systemd-centos-70> (1m34.29s).
```

**Comment by agperson** [comment]
On the master branch?

**Comment by jtimberman** [comment]
@agperson Are you experiencing a problem with a recipe in the chef-client cookbook? Or with the `chef-client` program running a recipe in the iis cookbook?

* [issues for chef, chef-client program](https://github.com/chef/chef/issues)
* [issues for iis cookbook](https://github.com/opscode-cookbooks/iis/issues)

This repository is specifically for the chef-client cookbook.

Cheers

**Comment by agperson** [comment]
Full output:
```
(agperson)$ git clone git@github.com:opscode-cookbooks/chef-client.git
Cloning into 'chef-client'...
remote: Counting objects: 2796, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 2796 (delta 6), reused 0 (delta 0), pack-reused 2778
Receiving objects: 100% (2796/2796), 586.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1357/1357), done.
Checking connectivity... done.
(agperson)$ cd chef-client/
(agperson)$ kitchen converge service-systemd-centos-7
-----> Starting Kitchen (v1.3.1)
-----> Creating <service-systemd-centos-70>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opscode-centos-7.0'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: service-systemd-centos-70_default_1426009690925_22145
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 => 2222 (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...    default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection timeout. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if its present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       Vagrant instance <service-systemd-centos-70> created.
       Finished creating <service-systemd-centos-70> (0m31.67s).
-----> Converging <service-systemd-centos-70>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       downloading https://www.chef.io/chef/install.sh
         to file /tmp/install.sh
       trying wget...
       Downloading Chef  for el...
       downloading https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=7&m=x86_64
         to file /tmp/install.sh.8127/metadata.txt
       trying wget...
       url	https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-12.1.1-1.el6.x86_64.rpm
       md5	01e4e0e2688c297590134f4070956148
       sha256	1ed7d17df3f11069f19f31c6bbe4101b55334bf4ba6e96f8d022cb6750b48a63
       downloaded metadata file looks valid...
       downloading https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-12.1.1-1.el6.x86_64.rpm
         to file /tmp/install.sh.8127/chef-12.1.1-1.el6.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...
       Installing Chef
       installing with rpm...
       warning: /tmp/install.sh.8127/chef-12.1.1-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
       Preparing...                          ################################# [100%]
       Updating / installing...
################################# [100%]
       Thank you for installing Chef!
       Transferring files to <service-systemd-centos-70>
       Starting Chef Client, version 12.1.1
       Creating a new client identity for service-systemd-centos-70 using the validator key.
       [2015-03-10T17:49:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-03-10T17:49:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["chef-client::systemd_service"]
       [2015-03-10T17:49:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - chef-client
         - cron
         - logrotate
         - windows
         - chef_handler
         - nagios
         - apache2
         - build-essential
         - php
         - nginx
         - nginx_simplecgi
         - yum-epel
         - nrpe
         - iptables
         - xml
         - mysql
         - iis
         - apt
         - bluepill
         - ohai
         - runit
         - perl
         - yum
         - chef-sugar
         - yum-mysql-community
         - smf
         - rsyslog
         - rbac
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb
       ================================================================================

       NameError
       ---------
       uninitialized constant Opscode::IIS::Helper::Windows

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb:31:in `<module:Helper>'
         /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb:24:in `<module:IIS>'
         /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb:23:in `<module:Opscode>'
         /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb:22:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/iis/libraries/helper.rb:

        24:      module Helper
        25:        if RUBY_PLATFORM =~ /mswin|mingw32|windows/
        26:          require 'chef/win32/version'
        27:        end
        28:
        29:        require 'rexml/document'
        30:        include REXML
        31>>       include Windows::Helper
        32:
        33:        def self.older_than_windows2008r2?
        34:          if RUBY_PLATFORM =~ /mswin|mingw32|windows/
        35:            win_version = Chef::ReservedNames::Win32::Version.new
        36:            win_version.windows_server_2008? ||
        37:            win_version.windows_vista? ||
        38:            win_version.windows_server_2003_r2? ||
        39:            win_version.windows_home_server? ||
        40:            win_version.windows_server_2003? ||


       Running handlers:
       [2015-03-10T17:50:02+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-10T17:50:02+00:00] ERROR: Exception handlers complete
       [2015-03-10T17:50:02+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 59.255943537 seconds
       [2015-03-10T17:50:02+00:00] ERROR: uninitialized constant Opscode::IIS::Helper::Windows
       [2015-03-10T17:50:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <service-systemd-centos-70>.
>>>>>> Please see .kitchen/logs/service-systemd-centos-70.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by btm** [comment]
chef-client master, with a couple edits to the kitchen yaml to get the latest chef-client and make sure IIS got included. You're getting a much larger run list than I am.

```
btm@btm-mbp:~/src/chef-client [master] $ git diff
diff --git a/.kitchen.yml b/.kitchen.yml
index 62b3639..a550df8 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -3,6 +3,7 @@ driver:
 
 provisioner:
   name: chef_zero
+  require_chef_omnibus: latest
 
 platforms:
   - name: centos-5.11
diff --git a/metadata.rb b/metadata.rb
index 8008002..aa014a3 100644
--- a/metadata.rb
+++ b/metadata.rb
@@ -37,3 +37,4 @@ suggests 'runit'
 depends 'cron', '>= 1.2.0'
 depends 'logrotate', '>= 1.2.0'
 depends 'windows', '~> 1.11'
+depends 'iis', '~> 4.1.0'
```

```       [2015-03-10T17:41:33+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["chef-client::systemd_service"]
       Synchronizing Cookbooks:
         - cron
         - logrotate
         - chef_handler
         - windows
         - iis
         - chef-client
       Compiling Cookbooks...
       Converging 8 resources
       Recipe: chef-client::systemd_service
         * directory[/var/run/chef] action create (up to date)
         * directory[/var/cache/chef] action create (up to date)
         * directory[/var/lib/chef] action create (up to date)
        (up to date)
         * directory[/etc/chef] action create (up to date)
         * template[/etc/systemd/system/chef-client.service] action create (up to date)
         * template[/etc/sysconfig/chef-client] action create (up to date)
        (up to date)
        (up to date)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/9 resources updated in 7.849033888 seconds
       Finished converging <service-systemd-centos-70> (1m38.28s).
-----> Kitchen is finished. (1m38.87s)
```

**Comment by btm** [comment]
@agperson what's your Berksfile.lock look like? Have you tried removing it?

**Comment by agperson** [comment]
That is strange that we are getting such different results.  Running Test Kitchen is generating the Berksfile.lock, I'm not doing anything myself.  I'm using all the ChefDK tools, and I reinstalled them from scratch a week or two ago.  The cookbook dependency chain looks like: windows -> chef_handler -> nagios -> php -> iis

The complete Berksfile.lock is:
```
DEPENDENCIES
  apt
  chef-client
    path: .
    metadata: true
  runit

GRAPH
  apache2 (3.0.1)
    iptables (>= 0.0.0)
    logrotate (>= 0.0.0)
  apt (2.6.1)
  bluepill (2.3.1)
    rsyslog (>= 0.0.0)
  build-essential (2.1.3)
  chef-client (4.2.4)
    cron (>= 1.2.0)
    logrotate (>= 1.2.0)
    windows (~> 1.11)
  chef-sugar (2.5.0)
  chef_handler (1.1.9)
    nagios (>= 0.0.0)
  cron (1.6.1)
  iis (4.1.0)
    windows (>= 1.34.6)
  iptables (0.14.1)
  logrotate (1.9.0)
  mysql (6.0.15)
    smf (>= 0.0.0)
    yum-mysql-community (>= 0.0.0)
  nagios (7.0.2)
    apache2 (>= 2.0)
    build-essential (>= 0.0.0)
    nginx (>= 0.0.0)
    nginx_simplecgi (>= 0.0.0)
    nrpe (>= 0.0.0)
    php (>= 0.0.0)
    yum-epel (>= 0.0.0)
  nginx (2.7.4)
    apt (~> 2.2)
    bluepill (~> 2.3)
    build-essential (~> 2.0)
    ohai (~> 2.0)
    runit (~> 1.2)
    yum-epel (~> 0.3)
  nginx_simplecgi (0.1.2)
    bluepill (>= 0.0.0)
    nginx (>= 0.0.0)
    perl (>= 0.0.0)
    runit (>= 0.0.0)
  nrpe (1.4.10)
    build-essential (>= 0.0.0)
    yum-epel (>= 0.0.0)
  ohai (2.0.1)
  perl (1.2.4)
  php (1.5.0)
    build-essential (>= 0.0.0)
    iis (>= 0.0.0)
    mysql (>= 0.0.0)
    windows (>= 0.0.0)
    xml (>= 0.0.0)
    yum-epel (>= 0.0.0)
  rbac (1.0.2)
  resource-control (0.1.1)
  rsyslog (1.15.0)
  runit (1.5.16)
    build-essential (>= 0.0.0)
    yum (~> 3.0)
    yum-epel (>= 0.0.0)
  smf (2.2.5)
    rbac (>= 1.0.1)
    resource-control (>= 0.0.0)
  windows (1.36.6)
    chef_handler (>= 0.0.0)
  xml (1.2.13)
    build-essential (>= 0.0.0)
    chef-sugar (>= 0.0.0)
  yum (3.5.3)
  yum-epel (0.6.0)
    yum (~> 3.0)
  yum-mysql-community (0.1.13)
    yum (>= 3.0)
```

**Comment by jtimberman** [comment]
Wow. That lock file doesn't make sense. I did the exact same things - git clone, cd, kitchen converge.

https://gist.github.com/jtimberman/ca3e44d570cc7911e9f6

**Comment by btm** [comment]
@agperson where are you getting chef_handler from? It's only [1.1.7 in master](https://github.com/opscode-cookbooks/chef_handler/blob/master/metadata.rb#L7) and it doesn't look like it has ever had dependencies (including nagios), your dependency graph shows 1.1.9.

**Comment by agperson** [comment]
:blush: Thanks for helping me work through this and track down the problem. Apologies both for taking your time and for assuming your cookbook was insane when it was actually my colleagues!

Elsewhere someone had forked chef_handler and added to it, bumping the version and uploading it to our internal Chef server.  Running berks on *that* repo downloaded the "new" version from the internal API server and cached it under `~/.berkshelf/cookbooks`.  Running berks on this cookbook apparently found the bad version locally cached and trusted it over what was returned by the API server specified in the Berksfile.  Which...seems like a design flaw, but not yours. :)
