### ISSUE TITLE
chef-client won't start in Cent OS  "couldn't find HOME environment" in path_helper.rb

### ISSUE THREAD

**Issue by ikuwow** [opscode-cookbooks/chef-client#301]
`chef-client` won't start in Cent OS 6.6 with run_list "chef-client::init_service".

```
  * service[chef-client] action start

    ================================================================================
    Error executing action `start` on resource 'service[chef-client]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service chef-client start ----
    STDOUT: chef-client を起動中: [失敗]
    STDERR: /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
    	from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `all_homes'
    	from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:161:in `home'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:36:in `gather_plist_dirs'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:40:in `<class:Macosx>'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:27:in `<class:Service>'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:26:in `<class:Provider>'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:25:in `<class:Chef>'
    	from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:24:in `<top (required)>'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/apps/chef/lib/chef/providers.rb:93:in `<top (required)>'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
    	from /usr/bin/chef-client:51:in `load'
    	from /usr/bin/chef-client:51:in `<main>'
    ---- End output of /sbin/service chef-client start ----
    Ran /sbin/service chef-client start returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef-client/recipes/init_service.rb

     32: service 'chef-client' do
     33:   supports :status => true, :restart => true
     34:   action [:enable, :start]
     35: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef-client/recipes/init_service.rb:32:in `from_file'

    service("chef-client") do
      action [:enable, :start]
      updated true
      supports {:status=>true, :restart=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "chef-client"
      enabled true
      pattern "chef-client"
      declared_type :service
      cookbook_name "chef-client"
      recipe_name "init_service"
    end
```

The result is same when manually type `service chef-client start`, with exit code 6.

And the question below seems to be exactly same problem on ec2.
http://stackoverflow.com/questions/29307097/knife-ec2-service-chef-client-wont-start-couldnt-find-home-environment

Is it a bug of the cookbook? 

I have made sure that the cookbook works fine in Ubuntu 14.10 and Debian 7.8 (test-kitchen and production). So it may be a problem specific to Cent OS.

**Comment by ikuwow** [comment]
It may be the bag of chef-client fixed in below:
https://github.com/chef/chef/commit/0d0fe7444461e31750ed28f3298657ff0c79272f

I'll try reinstall chef-client and apply the recipe again. I'll close this issue after worked correctly.

**Comment by ikuwow** [comment]
I reinstalled Chef 12.1.2 on centos node, and everything goes fine. Sorry for upsetting you.
