### ISSUE TITLE
chef-client::cron error,  "undefined method `join' for nil:NilClass"

### ISSUE THREAD

**Issue by gonzolively** [opscode-cookbooks/chef-client#304]
After unsuccessfully deploying the chef-client as an init based service (would not check in regularly to the server) I decided to go the 'cron' approach.  After reading the documentation and making minor tweaks to my 'roles' and the 'attributes.rb' file I am running into an issue with the error "undefined method `join' for nil:NilClass".  I have dug through the templates/cookbook and cannot seem to locate the issue.  I will post the stacktrace below.  Please let me know if more is needed.

```
   * template[/etc/sysconfig/chef-client] action create

     ================================================================================
     Error executing action `create` on resource 'template[/etc/sysconfig/chef-client]'
     ================================================================================

     Chef::Mixin::Template::TemplateError
     ------------------------------------
     undefined method `join' for nil:NilClass

     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/chef-client/recipes/cron.rb

      51:   template "/etc/#{conf_dir}/chef-client" do
      52:     source "#{dist_dir}/#{conf_dir}/chef-client.erb"
      53:     mode 0644
      54:   end
      55:

     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/chef-client/recipes/cron.rb:51:in `from_file'

     template("/etc/sysconfig/chef-client") do
       action "create"
       retries 0
       retry_delay 2
       default_guard_interpreter :default
       path "/etc/sysconfig/chef-client"
       backup 5
       atomic_update true
       source "suse/sysconfig/chef-client.erb"
       declared_type :template
       cookbook_name "chef-client"
       recipe_name "cron"
       mode 420
     end

     Template Context:
     -----------------
     on line #14
      12: SPLAY=<%= node["chef_client"]["splay"] %>
      13: # Any additional chef-client options.
      14: OPTIONS="<%= node["chef_client"]["daemon_options"].join(' ') %>"


 Running handlers:
 [2015-04-07T13:14:14-04:00] ERROR: Running exception handlers
 Running handlers complete
 [2015-04-07T13:14:14-04:00] ERROR: Exception handlers complete
 [2015-04-07T13:14:14-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
 Chef Client failed. 89 resources updated in 68.85221026 seconds
 [2015-04-07T13:14:14-04:00] ERROR:

 Chef::Mixin::Template::TemplateError (undefined method `join' for nil:NilClass) on line #14:

  12: SPLAY=<%= node["chef_client"]["splay"] %>
  13: # Any additional chef-client options.
  14: OPTIONS="<%= node["chef_client"]["daemon_options"].join(' ') %>"

   (erubis):14:in `block in evaluate'
   /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
   /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
   /opt/chef/embedded/apps/chef/lib/chef/mixin/template.rb:114:in `_render_template'
   /opt/chef/embedded/apps/chef/lib/chef/mixin/template.rb:100:in `render_template'
   /opt/chef/embedded/apps/chef/lib/chef/provider/template/content.rb:43:in `file_for_provider'
   /opt/chef/embedded/apps/chef/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
   /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:459:in `tempfile'
   /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:337:in `do_generate_content'
   /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:148:in `action_create'
   /opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
   /opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
   /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
   /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
   /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
   /opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
   /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
   /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
   /opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
   /opt/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
   /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
   /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
   /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
   /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
   /usr/bin/chef-client:51:in `load'
   /usr/bin/chef-client:51:in `<main>'


 [2015-04-07T13:14:14-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by gonzolively** [comment]
apparently it helps to read the whole chef-client documentation...solved by including 'cron' recipe
