### ISSUE TITLE
delete_validation.rb throws exception when there is no validation_key chef client config attribute

### ISSUE THREAD

**Issue by ozzyogkush** [opscode-cookbooks/chef-client#307]
The `delete_validation` recipe has a guard that checks for the existence of the client key file, but then attempts to delete the validation key without also checking for its existence, and assuming that the attribute `node['chef_client']['config']['validation_key']` even has a value. It should check for the existence of the attribute and the validation key at minimum, in addition to the client key.

```
==> default: ArgumentError
==> default: -------------
==> default: You must supply a name when declaring a file resource
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /etc/chef/chef-solo-1/cookbooks/chef-client/recipes/delete_validation.rb:25:in `from_file'
==> default:   /etc/chef/chef-solo-1/cookbooks/pet360-base/recipes/default.rb:9:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /etc/chef/chef-solo-1/cookbooks/chef-client/recipes/delete_validation.rb:
==> default: 
==> default:  18:  # limitations under the License.
==> default:  19:  
==> default:  20:  class ::Chef::Recipe
==> default:  21:    include ::Opscode::ChefClient::Helpers
==> default:  22:  end
==> default:  23:  
==> default:  24:  unless chef_server?
==> default:  25>>   file Chef::Config[:validation_key] do
==> default:  26:      action :delete
==> default:  27:      backup false
==> default:  28:      only_if { ::File.exists?(Chef::Config[:client_key]) }
==> default:  29:    end
==> default:  30:  end
==> default:  31:
```

This can happen when provisioning a Vagrant box using the `chef_zero` provisioner, where it fakes the validation key and you can't specify it as an option.

**Comment by ozzyogkush** [comment]
Latest PR fixes this issue.
